[package]
name = "single_thread_to_multi_thread"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "hello"
path = "hello/src/lib.rs"